
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: Q@simbu5uk
      POSTGRES_DB: dms_db
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=dms_db;Username=postgres;Password=Q@simbu5uk;"
      Elasticsearch__Url: "http://host.docker.internal:9200"